import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { Weather } from "@/components/weather"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Kira.town",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 border-b flex align-center justify-between text-2xl">
          <div className="flex items-center">
            <Link href="/">
              <h1 className="mr-6 font-black text-pink-600 hover:text-green-400">
                Kira.town
              </h1>
            </Link>
            <div className="space-x-4">
              <Link href="/wordle">Wordle</Link>
              <Link href="/bookshelf">Bookshelf</Link>
            </div>
          </div>
          <div className="flex items-center">
            <Weather />
          </div>
        </nav>
        <div className=" my-8 px-4 flex justify-center w-full">{children}</div>
      </body>
    </html>
  )
}
