import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Kira.town",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 border-b flex align-center text-2xl">
          {" "}
          <Link href="/">
            <h1 className="mr-6 font-black text-pink-600 hover:text-green-400">
              Kira.town
            </h1>
          </Link>
          <div className="space-x-4">
            <Link href="/wordle">Wordle</Link>
          </div>
        </nav>
        <div className="p-8 flex justify-center">{children}</div>
      </body>
    </html>
  )
}
